women
plot(women)
plot(women, type='p',pch=19)
plot(women, type='l')
plot(women, type='b',pch=19)
plot(women$weight,women$height, pch=15,xlab = 'WEIGHT',ylab = 'HEIGHT', col='red',type='b')
quantile(women$height, seq(0,1,.1))
boxplot(women$height, col = 'green') 
stem(women$height)
hist(women$weight)
hist(women$height, breaks=5,col=1:5)
(x=rnorm(100,50,10))
hist(x, freq = F)
lines(density(x))
gender
xlables = c('A','B','C','D')
labels2 = paste(xlables, round(x/sum(x),2)*100, sep="-")
pie(table(gender))
x=c(10,20,40,50)
pie(x,labels = labels2)
barplot(x,col = 1:4)

#corelation plot
pairs(women)
cor(women$height,women$weight)
cov(women$height,women$weight)
cor(mtcars)
pairs(mtcars[1:4])
x3 = runif(100,0,150)
x3 = ceiling(x3)
range(x3)
breaks = seq(0,150,15)
length(breaks)
x3.cut = cut(x3, breaks)
x3.cut
table(x3.cut)
cbind(table(x3.cut))
barplot(rbind(table(x3.cut)))
